// Port of tests/test_collision.py, same hand-computed expectations, plus a
// Python-vs-Swift depth parity spot check on seeded random pairs.

import Dispatch
import Foundation
import XCTest
@testable import PackPhysics

private func box(_ center: Vec3, _ halfExtents: Vec3, axes: Mat3 = .identity, id: String = "b") -> OBB {
    OBB(center: center, axes: axes, halfExtents: halfExtents, id: id)
}

/// Rotation about Z (Python `rotz`), stored by column.
private func rotZ(_ deg: Double) -> Mat3 {
    let r = deg * (Double.pi / 180), c = cos(r), s = sin(r)
    return Mat3(columns: Vec3(c, s, 0), Vec3(-s, c, 0), Vec3(0, 0, 1))
}

/// Rotation about X (Python `rotx`), stored by column.
private func rotX(_ deg: Double) -> Mat3 {
    let r = deg * (Double.pi / 180), c = cos(r), s = sin(r)
    return Mat3(columns: Vec3(1, 0, 0), Vec3(0, c, s), Vec3(0, -s, c))
}

private func vabs(_ v: Vec3) -> Vec3 { Vec3(abs(v.x), abs(v.y), abs(v.z)) }

/// Overlap of a/b projected on `axis` (independent of the SAT code under test).
private func projectedOverlap(_ axis: Vec3, _ a: OBB, _ b: OBB) -> Double {
    let ra = dot(vabs(a.axes.transposeMultiply(axis)), a.halfExtents)
    let rb = dot(vabs(b.axes.transposeMultiply(axis)), b.halfExtents)
    return ra + rb - abs(dot(axis, b.center - a.center))
}

private func faceAxes(_ a: OBB, _ b: OBB) -> [Vec3] {
    (0..<3).map { a.axes.column($0) } + (0..<3).map { b.axes.column($0) }
}

/// Deterministic 64-bit LCG (PCG's multiplier/increment); `SystemRandomNumberGenerator`
/// is not seedable, and the Python generator script uses these exact constants.
private struct LCG {
    private var s: UInt64
    init(seed: UInt64) { s = seed }

    mutating func next() -> Double {
        s = s &* 6364136223846793005 &+ 1442695040888963407
        return Double(s >> 11) * 0x1p-53
    }

    mutating func uniform(_ lo: Double, _ hi: Double) -> Double { lo + (hi - lo) * next() }
}

private func container() -> Container { Container(id: "c", dimensions: Vec3(4, 4, 4)) }

/// 2*nPairs random boxes; pair p is objects (2p, 2p+1). Draw order (3 quaternion, 3 dims,
/// 3 position per box) is part of the contract: `pythonDepths` below was generated by
/// replaying this exact generator in Python, so changing it invalidates that table.
private func randomObjects(count: Int) -> [SceneObject] {
    var rng = LCG(seed: 20260912)
    return (0..<count).map { k in
        let u1 = rng.next(), u2 = rng.next(), u3 = rng.next()
        let s1 = (1.0 - u1).squareRoot(), s2 = u1.squareRoot()
        let q = Quat(x: s1 * sin(2 * Double.pi * u2), y: s1 * cos(2 * Double.pi * u2),
                     z: s2 * sin(2 * Double.pi * u3), w: s2 * cos(2 * Double.pi * u3))
        let dims = Vec3(rng.uniform(0.02, 0.5), rng.uniform(0.02, 0.5), rng.uniform(0.02, 0.5))
        let pos = Vec3(rng.uniform(-0.35, 0.35), rng.uniform(-0.35, 0.35), rng.uniform(-0.35, 0.35))
        return SceneObject(id: "o\(k)", dimensions: dims, position: pos, rotation: q)
    }
}

final class CollisionTests: XCTestCase {
    // MARK: - no collision

    func testFarApart() {
        let a = box(Vec3(0, 0, 0), Vec3(1, 1, 1), id: "a")
        let b = box(Vec3(100, 100, 100), Vec3(1, 1, 1), id: "b")
        let res = checkCollision(a, b)
        XCTAssertFalse(res.colliding)
        XCTAssertEqual(res.penetrationDepthM, 0.0)
        XCTAssertNil(res.axis)
        XCTAssertNil(res.contactPoint)
        XCTAssertEqual(res.aId, "a")
        XCTAssertEqual(res.bId, "b")
        XCTAssertFalse(aabbOverlap(a, b))
    }

    // MARK: - face-face

    func testAxisAlignedOverlap() {
        // Both 2x2x2 cubes (half-extent 1), B offset 1.5 along X: overlap = 1+1-1.5 = 0.5
        let a = box(Vec3(0, 0, 0), Vec3(1, 1, 1), id: "a")
        let b = box(Vec3(1.5, 0, 0), Vec3(1, 1, 1), id: "b")
        let res = checkCollision(a, b)
        XCTAssertTrue(res.colliding)
        XCTAssertEqual(res.penetrationDepthM, 0.5, accuracy: 1e-6)
        let axis = try! XCTUnwrap(res.axis)
        XCTAssertEqual(abs(axis.x), 1, accuracy: 1e-9)
        XCTAssertEqual(abs(axis.y), 0, accuracy: 1e-9)
        XCTAssertEqual(abs(axis.z), 0, accuracy: 1e-9)
        XCTAssertEqual(axis.x, 1, accuracy: 1e-9)  // oriented A -> B
        XCTAssertTrue(aabbOverlap(a, b))
        // Contact point: midpoint of [0.5, 1] on X, centers' midpoint elsewhere.
        let contact = try! XCTUnwrap(res.contactPoint)
        XCTAssertEqual(contact.x, 0.75, accuracy: 1e-12)
        XCTAssertEqual(contact.y, 0.0, accuracy: 1e-12)
        XCTAssertEqual(contact.z, 0.0, accuracy: 1e-12)
    }

    // MARK: - 45 degree rotation

    func testRotatedBoxCollides() throws {
        // A axis-aligned cube at origin; B same size rotated 45 deg about Z, close enough
        // along X that its rotated corner pokes into A.
        let half = (Double.pi / 4) / 2  // 45 deg about Z -> q = (0, 0, sin(22.5), cos(22.5))
        let a = try obbFrom(SceneObject(id: "a", dimensions: Vec3(2, 2, 2), position: Vec3(0, 0, 0)))
        let b = try obbFrom(SceneObject(id: "b", dimensions: Vec3(2, 2, 2), position: Vec3(1.8, 0, 0),
                                        rotation: Quat(x: 0, y: 0, z: sin(half), w: cos(half))))
        let res = checkCollision(a, b)
        XCTAssertTrue(res.colliding)
        XCTAssertGreaterThan(res.penetrationDepthM, 0.0)
    }

    func testRotatedBoxNoCollisionWhenFar() throws {
        let half = (Double.pi / 4) / 2
        let a = try obbFrom(SceneObject(id: "a", dimensions: Vec3(2, 2, 2), position: Vec3(0, 0, 0)))
        let b = try obbFrom(SceneObject(id: "b", dimensions: Vec3(2, 2, 2), position: Vec3(5, 0, 0),
                                        rotation: Quat(x: 0, y: 0, z: sin(half), w: cos(half))))
        XCTAssertFalse(checkCollision(a, b).colliding)
    }

    // MARK: - containment

    func testSmallBoxInsideBigBox() throws {
        let big = box(Vec3(0, 0, 0), Vec3(5, 5, 5), id: "big")
        let small = box(Vec3(0.5, 0, 0), Vec3(1, 1, 1), id: "small")
        let res = checkCollision(big, small)
        XCTAssertTrue(res.colliding)
        // overlap along X = 5+1-0.5 = 5.5 ; Y, Z = 5+1-0 = 6 ; min is X
        XCTAssertEqual(res.penetrationDepthM, 5.5, accuracy: 1e-6)
        let axis = try XCTUnwrap(res.axis)
        XCTAssertEqual(abs(axis.x), 1, accuracy: 1e-9)
        XCTAssertEqual(abs(axis.y), 0, accuracy: 1e-9)
        XCTAssertEqual(abs(axis.z), 0, accuracy: 1e-9)
    }

    // MARK: - edge-edge (only a cross axis separates)

    /// Two rods rotated relative to each other so that only one of the 9 cross-product axes
    /// separates them -- all 6 face axes still show overlap. Verified numerically, not
    /// hand-derivable in closed form, so the assertions are booleans plus "the reported axis
    /// is not parallel to any face axis".
    private func edgeEdgePair(_ t: Double) -> (OBB, OBB) {
        let ra = Mat3.identity
        let rb = rotZ(45) * rotX(45)
        let u = cross(ra.column(0), rb.column(1))
        let un = u / length(u)
        return (OBB(center: .zero, axes: ra, halfExtents: Vec3(1.0, 0.05, 0.05), id: "a"),
                OBB(center: un * t, axes: rb, halfExtents: Vec3(0.05, 0.05, 1.0), id: "b"))
    }

    func testCollidingViaCrossAxis() throws {
        let (a, b) = edgeEdgePair(0.1)
        let res = checkCollision(a, b)
        XCTAssertTrue(res.colliding)
        let axis = try XCTUnwrap(res.axis)
        for face in faceAxes(a, b) {
            XCTAssertLessThan(abs(dot(axis, face)), 0.9)  // not (anti)parallel to a face axis
        }
    }

    func testNotCollidingButAllFaceAxesStillOverlap() {
        let (a, b) = edgeEdgePair(0.5)
        XCTAssertFalse(checkCollision(a, b).colliding)
        for face in faceAxes(a, b) {
            XCTAssertGreaterThan(projectedOverlap(face, a, b), 0.0)  // faces alone say "colliding"
        }
    }

    /// Second cross-axis-only case (30 deg about Z, 60 deg about X).
    private func edgeEdge3060Pair(_ t: Double) -> (OBB, OBB) {
        let ra = Mat3.identity
        let rb = rotZ(30) * rotX(60)
        let u = cross(ra.column(0), rb.column(2))
        let un = u / length(u)
        return (OBB(center: .zero, axes: ra, halfExtents: Vec3(1.0, 0.05, 0.05), id: "a"),
                OBB(center: un * t, axes: rb, halfExtents: Vec3(0.05, 0.05, 1.0), id: "b"))
    }

    func testEdgeEdge3060CollidingWhenClose() {
        let (a, b) = edgeEdge3060Pair(0.05)
        XCTAssertTrue(checkCollision(a, b).colliding)
    }

    func testEdgeEdge3060SeparatedOnlyByCrossAxis() {
        let (a, b) = edgeEdge3060Pair(0.2)
        XCTAssertFalse(checkCollision(a, b).colliding)
        for face in faceAxes(a, b) {
            XCTAssertGreaterThan(projectedOverlap(face, a, b), 0.0)
        }
    }

    // MARK: - corner cases

    func testExactCornerTouchNotColliding() {
        let a = box(Vec3(0, 0, 0), Vec3(1, 1, 1), id: "a")
        let b = box(Vec3(2, 2, 2), Vec3(1, 1, 1), id: "b")
        XCTAssertFalse(checkCollision(a, b).colliding)
    }

    func testNearCornerTouchColliding() {
        let a = box(Vec3(0, 0, 0), Vec3(1, 1, 1), id: "a")
        let b = box(Vec3(1.999, 1.999, 1.999), Vec3(1, 1, 1), id: "b")
        let res = checkCollision(a, b)
        XCTAssertTrue(res.colliding)
        XCTAssertEqual(res.penetrationDepthM, 0.001, accuracy: 1e-6)
    }

    // MARK: - touching and epsilon semantics

    func testExactlyTouchingNotColliding() {
        let a = box(Vec3(0, 0, 0), Vec3(1, 1, 1), id: "a")
        let b = box(Vec3(2, 0, 0), Vec3(1, 1, 1), id: "b")  // faces share the plane x = 1
        let res = checkCollision(a, b)
        XCTAssertFalse(res.colliding)
        XCTAssertEqual(res.penetrationDepthM, 0.0)
    }

    func testTinyOverlapBeyondEpsilonIsColliding() {
        let a = box(Vec3(0, 0, 0), Vec3(1, 1, 1), id: "a")
        let b = box(Vec3(2 - 1e-4, 0, 0), Vec3(1, 1, 1), id: "b")
        let res = checkCollision(a, b, epsilon: 1e-6)
        XCTAssertTrue(res.colliding)
        XCTAssertEqual(res.penetrationDepthM, 1e-4, accuracy: 1e-6)
    }

    func testOverlapWithinEpsilonIsNotColliding() {
        let a = box(Vec3(0, 0, 0), Vec3(1, 1, 1), id: "a")
        let b = box(Vec3(2 - 1e-7, 0, 0), Vec3(1, 1, 1), id: "b")
        XCTAssertFalse(checkCollision(a, b, epsilon: 1e-6).colliding)
    }

    // MARK: - parallel edges (all 9 cross axes null)

    func testParallelGapAlongXNotColliding() {
        let a = box(Vec3(0, 0, 0), Vec3(0.1, 0.1, 0.1), id: "a")
        let b = box(Vec3(0.25, 0, 0), Vec3(0.1, 0.1, 0.1), id: "b")  // 0.05 m gap along +x
        let res = checkCollision(a, b)
        XCTAssertFalse(res.colliding)
        XCTAssertEqual(res.penetrationDepthM, 0.0)
    }

    func testParallelKnownOverlapIsExact() throws {
        let a = box(Vec3(0, 0, 0), Vec3(0.1, 0.1, 0.1), id: "a")
        let b = box(Vec3(0.19, 0, 0), Vec3(0.1, 0.1, 0.1), id: "b")  // overlap = 0.2 - 0.19
        let res = checkCollision(a, b)
        XCTAssertTrue(res.colliding)
        XCTAssertEqual(res.penetrationDepthM, 0.01, accuracy: 1e-9)
        let axis = try XCTUnwrap(res.axis)
        XCTAssertEqual(axis.x, 1, accuracy: 1e-12)
        XCTAssertEqual(axis.y, 0, accuracy: 1e-12)
        XCTAssertEqual(axis.z, 0, accuracy: 1e-12)
    }

    // MARK: - scene level

    func testCollideSceneFindsTheOneEngineeredOverlap() throws {
        let g = try precompute(Parity.scene(named: "fixture:scene_with_collision"))
        let results = collideScene(g)
        XCTAssertEqual(results.map { [$0.aId, $0.bId].sorted() }, [["laptop", "shoe"]])
        // fixture: shoe shifted so it overlaps the laptop by exactly 0.02 m
        XCTAssertEqual(results[0].penetrationDepthM, 0.02, accuracy: 1e-9)
    }

    func testValidSceneHasNoCollisions() throws {
        let g = try precompute(Parity.scene(named: "fixture:valid_packed_scene"))
        XCTAssertEqual(collideScene(g).count, 0)
    }

    func testEmptyPairs() throws {
        let g = try precompute(Scene(container: container(), objects: randomObjects(count: 2)))
        XCTAssertEqual(checkPairs(g, []).count, 0)
    }

    // MARK: - Python parity, symmetry and self-collision on random pairs

    /// `physics.collision.check_collision` depths from the Python reference for the same 100
    /// pairs: the LCG above (same constants, same draw order) and `obb_from` were replayed in
    /// Python and the depths pasted here at full precision. To regenerate, port `LCG` and
    /// `randomObjects` to ~20 lines of Python and print "%.17g" of each depth.
    /// 0 means "not colliding"; every real depth is > epsilon = 1e-6.
    private static let pythonDepths: [Double] = [
        0.15293218526817928, 0, 0, 0,
        0, 0, 0, 0.060897228463797491,
        0, 0, 0.21896711372727964, 0,
        0, 0, 0, 0.093081542370907794,
        0, 0, 0, 0,
        0, 0, 0, 0,
        0, 0, 0, 0,
        0.18960865791171927, 0, 0, 0,
        0, 0, 0, 0.011385476503758596,
        0, 0, 0.057137470436555482, 0,
        0, 0, 0, 0,
        0, 0, 0.27770272551898617, 0,
        0.077979183679599759, 0, 0, 0.030612682031873974,
        0.15412613324462621, 0, 0, 0,
        0, 0, 0, 0,
        0.072791077286832054, 0.11175158429239015, 0.011861433124259373, 0,
        0, 0, 0, 0,
        0.01512877859834723, 0, 0, 0,
        0, 0.058968447846462324, 0.10450256596708205, 0,
        0, 0, 0, 0,
        0, 0, 0.16179954404494559, 0,
        0, 0, 0.1527932120029325, 0,
        0, 0, 0.014155864961504061, 0,
        0, 0, 0, 0,
        0, 0, 0, 0,
    ]

    func test100RandomPairsMatchPythonAndAreSymmetric() throws {
        let nPairs = 100
        let g = try precompute(Scene(container: container(), objects: randomObjects(count: 2 * nPairs)))
        let pairs = (0..<nPairs).map { (2 * $0, 2 * $0 + 1) }
        let batched = checkPairs(g, pairs)
        XCTAssertEqual(batched.count, nPairs)

        var nColliding = 0
        for p in 0..<nPairs {
            let a = g.obbs[2 * p], b = g.obbs[2 * p + 1]
            let res = batched[p]
            XCTAssertEqual(res, checkCollision(a, b), "pair \(p): checkPairs != checkCollision")
            XCTAssertEqual(res.aId, a.id)
            XCTAssertEqual(res.bId, b.id)

            // Python parity.
            let expected = Self.pythonDepths[p]
            XCTAssertEqual(res.colliding, expected > 0, "pair \(p): colliding disagrees with Python")
            XCTAssertEqual(res.penetrationDepthM, expected, accuracy: 1e-12, "pair \(p): depth")

            // Symmetry: same verdict, same depth, opposite MTV direction.
            let swapped = checkCollision(b, a)
            XCTAssertEqual(swapped.colliding, res.colliding, "pair \(p): asymmetric verdict")
            XCTAssertEqual(swapped.penetrationDepthM, res.penetrationDepthM, accuracy: 1e-12,
                           "pair \(p): asymmetric depth")
            if res.colliding {
                nColliding += 1
                let axis = try XCTUnwrap(res.axis)
                let back = try XCTUnwrap(swapped.axis)
                XCTAssertEqual(dot(axis, back), -1.0, accuracy: 1e-12, "pair \(p): axes not antiparallel")
                XCTAssertEqual(length(axis), 1.0, accuracy: 1e-12, "pair \(p): axis not unit")
            } else {
                XCTAssertNil(res.axis)
                XCTAssertNil(res.contactPoint)
            }

            // A box always collides with itself.
            XCTAssertTrue(checkCollision(a, a).colliding, "self-collision \(a.id)")
        }
        XCTAssertEqual(nColliding, 20)  // both branches genuinely exercised (Python agrees)
    }

    // MARK: - perf sanity

    /// Dense 20-box scene (0.20 m boxes on a 0.19 m grid + deterministic jitter -> 99 of the
    /// 190 pairs overlap). A bound, not a benchmark.
    func testDenseSceneUnderTwoMillisecondsPerCall() throws {
        let objects = (0..<20).map { k -> SceneObject in
            let grid = [k % 3, (k / 3) % 3, k / 9]
            let p = (0..<3).map { c in Double(grid[c]) * 0.19 + Double(((k * 7 + c * 3) % 11) - 5) * 0.001 }
            return SceneObject(id: "o\(k)", dimensions: Vec3(0.2, 0.2, 0.2), position: Vec3(p[0], p[1], p[2]))
        }
        let g = try precompute(Scene(container: container(), objects: objects))
        XCTAssertEqual(collideScene(g).count, 99)  // same count Python reports for this scene

        let calls = 50
        let t0 = DispatchTime.now().uptimeNanoseconds
        var total = 0
        for _ in 0..<calls { total += collideScene(g).count }
        let msPerCall = Double(DispatchTime.now().uptimeNanoseconds - t0) / 1e6 / Double(calls)
        XCTAssertEqual(total, 99 * calls)
        // Measured: 0.041 ms/call release, 1.44 ms/call debug. The -Onone build spends ~35x
        // longer on unoptimized SIMD3 arithmetic and the per-pair result array, which the 2 ms
        // target would leave no headroom for on a loaded machine -- so the debug bound is
        // loosened and only release holds the real budget.
        #if DEBUG
        let budgetMs = 8.0
        #else
        let budgetMs = 0.5
        #endif
        print("collideScene, dense 20-box scene: \(msPerCall) ms/call over \(calls) calls (budget \(budgetMs) ms)")
        XCTAssertLessThan(msPerCall, budgetMs, "collideScene took \(msPerCall) ms/call")
    }
}
